### ISSUE TITLE
how to deploy to linux?

### ISSUE THREAD

**Issue by githall** [InstantASP/Plato#12]
how to deploy to linux ubuntu 18.04?

**Comment by InstantASP** [comment]
Hi There,

Thank you so much for your question. I'm afraid at the moment Plato has only been tested on Windows. We do plan to introduce Linux support once we update to .NET Core 3.0 for the Plato 1.1.0 release. If your able to wait a few weeks our story around Linux support will improve. Would you be willing to help us test the Linux support once introduced?

For some background, whilst Plato is cross platform (Plato is 100% .NET Core 2.0 standard libraries), Plato.Internal.Drawing does have a dependency on the [Windows Compatibility Pack ](https://devblogs.microsoft.com/dotnet/announcing-the-windows-compatibility-pack-for-net-core/) package as Plato.Internal.Drawing uses System.Drawing / GDI+. This is something we plan to improve by moving to a cross platform friendly image processing library such as ImageSharp, Magick.NET or SkiaSharp. Once this is complete Plato should work on Linus without any issues. Please do check back often for further updates on this. 

Thank you for checking out Plato :)

**Comment by githall** [comment]
Yes.I'm willing to help you test the Linux support once introduced.I have a host ubuntu18.04+jexus+mono env.
jexus is a http web server.it's site is https://www.jexus.org/

**Comment by ByronAP** [comment]
started work on PlatoCore.Drawing since I want to launch on linux

**Comment by InstantASP** [comment]
Hi @githall  & @ByronAP,

I'm going to close this issue and move all linux discussion for now at least to #24. 

We'll have 1.1.2 shipped this week and then finally Linux will be a focus :)

Thank you both for your interest and patience. If I can assist with anything of course don't hesitate to respond. Best wishes for now,

Ryan
