### ISSUE TITLE
How does this error occur?

### ISSUE THREAD

**Issue by githall** [InstantASP/Plato#14]
http://1.71.132.254:8888/u/1/admin

**Comment by InstantASP** [comment]
Hi There,

Thank you so much for using Plato. 

I'm afriad I don't see any error at http://1.71.132.254:8888/u/1/admin

I wonder however if the error you encountered could be related to the first time avatar / profile photo generation. The user avatars / photos are generated dynmically upon the first request and saved as a static image for performance for further requests. These images are saved typically to your {root}/Sites/{site-name}/images/ folder.

If a problem occurred generating the image upon the first request or the app didn't have permission to save the image to your sites/{site-name}/images folder an error may have occurred. I'm simply guessing here as I can't see the original error but wanted to offer some suggestions. 

If you take a look inside the "logs" folder within the Plato web site root you should see some log files which should include the original error you encoutnered. Do you see any hints within the log files? I would ask you don't post the logs here as they may contain sensitive information related to your service however they may help you identify the error and troubleshoot further. 

I'd love to know how your running Plato - is this under IIS on Windows or possibly Linux? If I can assist further or any other errors occur of course please don't hesitate to respond. 

Thanks again for using Plato and also for your pull request :)
