### ISSUE TITLE
Register and configure NSwag middleware - swagger.json is not found

### ISSUE THREAD

**Issue by alweish** [InstantASP/Plato#18]
Hi,

I am adding a RESTful API for some features that don't have an API like 'discuss' or 'questions', and I think that Swagger would be a very helpful addition.

I followed the regular steps to add and configure Swagger middleware as shown here:

[https://docs.microsoft.com/en-us/aspnet/core/tutorials/getting-started-with-nswag?view=aspnetcore-2.2&tabs=visual-studio]

It looks like swagger.json is not being generated, I tried to add it to the `client app`, tried to add it to `Plato.Internal.Hosting.Web`, Also tried adding a DocumentPath, but didn't work:

`            app.UseSwaggerUi3(options =>
            {
                options.DocumentPath = "/swagger/" + "v1" + "/swagger.json";
            });
  `
When i try to access, it's redirecting to `/moved`.

I feel like it's relevant to a conflict with Plato Middleware or Routes, 

Any Ideas to help to figure it out?

**Comment by InstantASP** [comment]
Hi There,

It's awesome to hear your adding some REST services to Plato. This is on the roadmap but a few months away currently. Any help you can provide would be awesome :)

With regards to your issue Plato will only serve static files from within the wwwroot folder. If you pop your swagger folder inside the wwwroot folder does this work? 

You should be able to leave your configured DocumentPath as is. This should look for the swagger folder inside the wwwroot folder. Please let me know if the issues persists. 

Regards,

Ryan

**Comment by alweish** [comment]
Thanks Ryan,

Worked after moving `app.UsePlato` after `app.UseSwaggerUi3`

**Comment by InstantASP** [comment]
Thank you so much for the update. I'm looking forward to having some time to spend on implementing swagger / open API support. I'm sure I'll learn from your contributions. Thanks again for helping improve Plato. If I can assist with anything don't hesitate to respond :)
