### ISSUE TITLE
Add new Language

### ISSUE THREAD

**Issue by alaawahbah** [InstantASP/Plato#19]
Hi..
How can I add new language Like (arabic,russan)
thanks in advance...

**Comment by InstantASP** [comment]
Thank you so much for your message. Apologies for my delay responding.

Whilst Plato does support localization we currently only have the English strings. Localizing Plato is not a trivial task as each module would need to be localized to your desired language. 

For example to localize Plato.Discuss you would need to make a copy of the the existing "en-US" folder within modules/Plato.Discuss/locales and rename this to say "zh-Hans" or "zh-Hant" depending on simplified or traditional translation. You can then add the english strings that appear within the Plato user interface to strings.json with the Chinese translation as the value. For example to localize the text "Post Topic", "New Post", & "Discuss" your modules/Plato.Discuss/locales/zh-Hans/strings.json file would look like so...

```
{
  "Strings": [
    {
      "Key": "Post Topic",
      "Value": "发表主题"
    },
    {
      "Key": "New Post",
      "Value": "最新帖子"
    },
    {
      "Key": "Discuss",
      "Value": "讨论"
    }
  ]
}

```

You would need to repeat this similar translation for each module. For example Plato.Articles, Plato.Questions etc. Once you've added a new folder to any modules locales folder you should see the name of that folder in this case "zh-Hans" appear for selection via the language drop down list on the Dashboard > Settings > General page. 

You can read more on how localization within Plato works here...

https://plato.instantasp.co.uk/docs/d/34/how-localisation-works

I hope this helps. It's great to see non-English users using Plato. I'm sorry we don't have a great story around localization at the moment. We will be improving this with community tooling and out of the box language packs during our 1.1.x milestones.  

If I can assist further with anything in the meantime please don't hesitate to respond. 

Best wishes and thanks for using Plato - Ryan
