### ISSUE TITLE
Typo in Docs and Articles reading time

### ISSUE THREAD

**Issue by KinaUna** [InstantASP/Plato#21]
There is a typo in the Docs module, the card-title says "Less then 1 minute to read", it should be "Less than a minute to read".

See here for an example: https://plato.instantasp.co.uk/docs/d/7/installing-plato

I tried to replace the text in Modules\Plato.Docs\Views\Shared\Components\Doc\Default.cshtml, line 29, rebuilt the solution and published it, but it still displays "then" instead of "than".

The same goes for Articles.

I searched the whole solution but found no other occurrences of "Less then". I am I missing something, or should I update strings.json in the Locales folder instead?

**Comment by InstantASP** [comment]
Hi There,

Thank you so much for reporting this. We have of course updated the code (https://github.com/InstantASP/Plato/commit/548e343025544c512af6221e4dac26b782e42a3c) 

You are correct and this typo should only appear in 2 place  Plato.Docs & Plato.Articles. 

I'm afraid changing this text within the views won't work for production environments as the views are pre-compiled for performance. Within production for the changes to take effect you would need to rebuild the Plato.Docs & Plato.Articles modules and re-deploy the updated `Plato.Docs\bin\{ReleaseType}\netstandard2.0\Plato.Docs.Views.dll` & `Plato.Articles\bin\{ReleaseType}\netstandard2.0\Plato.Articles.Views.dll` assemblies. 

If you change your installation to run in development mode by updating the web.config...

 `<environmentVariable name="ASPNETCORE_ENVIRONMENT" value="Development" />` 

This should load the views from disk and compile the views at run-time so your view changes should be reflected immediately without the need to recompile. Of course this is not the solution as this will impact performance but this may allow you to more easily test your changes locally before deploying to production. 

If your using Visual Studio you would be able to change the release type to "Debug" and the deploy type to "Development" to see view changes reflected immediately locally. 

I hope something here helps. If your still not able to get your changes deployed of course please don't hesitate to respond and I'll happily assist further. For now thank you so much for checking our Plato. We are working on our .NET Core 3.1 update and some exciting new modules which will be available in the coming weeks :)

I look forward to hearing from you and assisting further. Ryan

**Comment by KinaUna** [comment]
Thanks, that was a very good explanation, it now makes sense to me why it didn't change.

As an intermediate solution, I fixed the typo by adding a localization string.
That is, I in each project \locales\en-US\strings.json file I added this:
```
{
      "Key": "Less then 1 minute to read",
      "Value": "Less than 1 minute to read"
}
```
After deploying again the text was updated on the live site.

**Comment by InstantASP** [comment]
Great workaround 👍 

If you encounter any further issues of course please don't hesitate to pop a new issue here and we'll certainly assist further. Looking forward to sharing news on our 1.1 update very soon :)
