### ISSUE TITLE
Project Questions and Notes

### ISSUE THREAD

**Issue by VaclavElias** [InstantASP/Plato#22]
Hi,

1. I wasn't able to register (Google or individual account) to your website to give you my questions there :)
2. If I have got already an existing ASP.NET Core website, can I hook your Discussion module to my existing website, using default ASP.NET Core Identity and my default existing user/logins I already have?
   - if not, how complex it would be to create such an options, I might be able to do it myself, it could be another feature for your project but can you tell a complexity of such update? Are we talking about hours or days or weeks of work? This goes also to other modules, if I would like to hook e.g. Questions or Ideas module...
3. Is it possible to vote,rate on Discussion module replies like in Reddit?
   - if not, probably I could use Questions and just update Layout so it looks a bit like Discussion?

Thank you :)

**Comment by InstantASP** [comment]
Hi Vaclav,

Thank you so much for your questions :) I'm sincerely sorry for my delay responding. Things have been a bit busy over the last week getting ready for Plato 1.1.0 wich now targets .NET Core 3.1 :)

To assist with your questions...

- I wasn't able to register (Google or individual account) to your website to give you my questions there :)

I'm sorry to hear this. We will of course take a closer look at this ASAP. 

- If I have got already an existing ASP.NET Core website, can I hook your Discussion module to my existing website, using default ASP.NET Core Identity and my default existing user/logins I already have?

Plato also uses regular ASP.NET Core Identity for user authentication so I'm sure this should be very possible. Unfortunitly we don't have any good examples just yet - this is on the roadmap. 

Probably the easiest way to achieve this would be to create your own implementation of IUserStore and replacing our default implementation with your own concrete implementation that would point towards your existing user database. 

You would replace our implementation of IUserStore with your own implementation via the built-in dependency injection container provided by .NET Core. We register our implementation of IUserStore within the Modules\Plato.Users\StartUp.cs file. 

For example if you wanted to use the default entity framework user store within Plato.Users\StartUp.cs you would replace...

`services.TryAddScoped<IUserStore<User>, PlatoUserStore>();`

With...

services.AddScoped<IUserStore<User>, EntityFrameworkCoreUserStore<User>>();

You would then create EntityFrameworkCoreUserStore like so...

```
using System;
using System.Threading;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Identity.EntityFrameworkCore;
using WebApplication1.Data;

namespace WebApplication1
{

/// <summary>
/// A custom IUserStore implementation for Plato using EntityFramework
/// </summary>
/// <typeparam name="TUser"></typeparam>
public class EntityFrameworkCoreUserStore<TUser> :
    IUserStore<TUser> where TUser : IdentityUser<string>, new()
{

    private readonly UserStore<TUser> _userStore;

    public EntityFrameworkCoreUserStore(ApplicationDbContext dbContext)
    {
        _userStore = new UserStore<TUser>(dbContext);
    }

    public void Dispose()
    {
        _userStore.Dispose();
    }

    public async Task<string> GetUserIdAsync(TUser user, CancellationToken cancellationToken)
    {
        return await _userStore.GetUserIdAsync(user, cancellationToken);
    }

    public async Task<string> GetUserNameAsync(TUser user, CancellationToken cancellationToken)
    {
        return await _userStore.GetUserNameAsync(user, cancellationToken);
    }

    public async Task SetUserNameAsync(TUser user, string userName, CancellationToken cancellationToken)
    {
        await _userStore.SetUserNameAsync(user, userName, cancellationToken);
    }

    public async Task<string> GetNormalizedUserNameAsync(TUser user, CancellationToken cancellationToken)
    {
        return await _userStore.GetNormalizedUserNameAsync(user, cancellationToken);
    }

    public async Task SetNormalizedUserNameAsync(TUser user, string normalizedName,
        CancellationToken cancellationToken)
    {
        await _userStore.SetNormalizedUserNameAsync(user, normalizedName, cancellationToken);
    }

    public async Task<IdentityResult> CreateAsync(TUser user, CancellationToken cancellationToken)
    {
        return await _userStore.CreateAsync(user, cancellationToken);
    }

    public async Task<IdentityResult> UpdateAsync(TUser user, CancellationToken cancellationToken)
    {
        return await _userStore.UpdateAsync(user, cancellationToken);
    }

    public async Task<IdentityResult> DeleteAsync(TUser user, CancellationToken cancellationToken)
    {
        return await _userStore.DeleteAsync(user, cancellationToken);
    }

    public async Task<TUser> FindByIdAsync(string userId, CancellationToken cancellationToken)
    {
        return await _userStore.FindByIdAsync(userId, cancellationToken);
    }

    public async Task<TUser> FindByNameAsync(string normalizedUserName, CancellationToken cancellationToken)
    {
        return await _userStore.FindByNameAsync(normalizedUserName, cancellationToken);
    }
}
}
```

Please note I've not tested this code and more work may be required but wanted to give you a basic sense of the changes required to swap out the default user store for Plato. 

- Is it possible to vote,rate on Discussion module replies like in Reddit?
if not, probably I could use Questions and just update Layout so it looks a bit like Discussion?

This is very possible. You would need to enable the Plato.Discuss.Votes module. To enable this module visit the Admin dashboard and click Features on the left. Click Manage Features and search for Plato.Discuss.Votes - enable this feature. 

Once enabled you'll notice similar to questions you can upvote or downvote topics & topic replies. 

I hope the above examples are helpful. I'll make it a priority to provide a more complete example of how to integrate Plato into an existing user database. If I can assist with anything further or any questions around this of course please never hesitate to respond. 

Thank you for checking out Plato. I look forward to assisting further :)

Regards,

Ryan

**Comment by VaclavElias** [comment]
Thank you Ryan, no problem, I totally understand.

I am planning to use it with ASP.NET Core 3.1 so the timing is just great.

I just needed to point a finger to some direction.

I will share back my results once I start working on this.

Thanks again, this is very helpful.

**Comment by InstantASP** [comment]
Hi @VaclavElias,

Just closing this issue to keep things tidy. If I can assist with any authenticaiton issues still of course please don't hesitate to respond. Best wishes for now,

Ryan
