### ISSUE TITLE
Images in the Project

### ISSUE THREAD

**Issue by VaclavElias** [InstantASP/Plato#25]
Not important but those images in \src\Web\Sites\Plato\images\ are png but I think they are actually bmp. 

In any case, if converted to jpg they should save 226MB to 3MB :)

**Comment by InstantASP** [comment]
Thank you so much for reporting this. 

I hadn't realized those images had grown so large. They could certainly use some optimization.  We create those profile images dynamically upon the first request via [InMemoryLetterRenderer](https://github.com/InstantASP/Plato/blob/master/src/Core/Drawing/Letters/InMemoryLetterRenderer.cs). You can safely deleted all those profile images and [InMemoryLetterRenderer](https://github.com/InstantASP/Plato/blob/master/src/Core/Drawing/Letters/InMemoryLetterRenderer.cs) will create each image again upon the next request. Once created for performance reasons they are of course then served as static files from the file system. 

We'll look at creating a different implementation of InMemoryLetterRenderer that will produce a much more optimized image. I'll pop an update here once this is addressed so you can take a closer look and ensure everything looks OK. 

Thank you again for taking the time to report this Vaclav . If you spot anything else of course please let me know by posting a new issue. 

P.S. The way we create images will change in the near future. We currently use a port of  System.Drawing from Microsoft for .NET Core. Unfortunitly this port uses GDI+ under the covers which is a windows thing and won't work on Linux. We want to add Linux hosting support so will be moving to a more generic cross platform image library very soon. If we can't find a good fit in terms of features & security we may even remove dynamic image generation all together in favour of providing the static files at release time. If you have a preference of course please let me know. 

Thank you again for checking our Plato Vaclav :)

Regards,

Ryan

**Comment by VaclavElias** [comment]
Thank you for an insight!

**Comment by InstantASP** [comment]
Hi Vaclav,

I hope things are well. I just wanted to confirm we resolved this issue a few weeks back and will shortly be releaseing Plato 1.1.1 which includes this fix. We managed to reduce each automatically generated profile photo from around 300kb to around 3kb. 

For now we'll close this issue as hopefully thiss issue should be resolved with our forthcoming 1.1.1 update. If you beleive the size issue still persists of course please don't hesitate to respond here. 

Thank you again for taking the time to report this Vaclav and for trying Plato. If I can assist with anything further please never hesitate to respond. 

Best wishes for now,

Ryan
