### ISSUE TITLE
Publish does not publish Module dlls

### ISSUE THREAD

**Issue by robsiera** [InstantASP/Plato#29]
I followed the various, clear, instructions on how to Publish a new Plato installation. But whatever I do, the dlls of the Modules are never published.  Can you confirm that this approach is still working in the latest version?

**Comment by InstantASP** [comment]
Hi Rob,

I'm sincerely sorry to hear this. I've been testing the publishing today and can't seem reproduce this. Can you confirm you built the solution via Visual Studio witin "Production" mode before publishing Plato. During Publishing we will only copy the "/bin/Release" folder for each module and not the "/bin/Debug" folder. 

Does this help Rob? If this resolves the problem please let me know or of course don't hesitate to respond if the issue persists.

**Comment by robsiera** [comment]
Ryan, thanks for confirming! 
I tried again, using your Golden Tip.
"Rebuild all, while being in 'Production mode'" was my missing link.
I'm getting the Web Setup now. So, all good.

BTW, yesterday I tried to create an account to give feedback on the documentation. But I never received the confirmation email.

**Comment by InstantASP** [comment]
Hi Rob,

I'm so pleased to hear this helped. Thank you for the confirmation. I'm sorry you had to run into issues during publishing as I know this can take quite some time. I'll ensure our docs are updated to make this step clear and will also look at ways to see if we can't automate the creation of the release assemblies during the publishing phase. 

With regards to the account confirmation email Rob I'm sincerely sorry about this. We've launched quite a large update for our site today getting things ready for our Plato 1.1.1 tomorrow. We broke the emails yesterday and the update today should resolve this and clear the email queue. Hopefully you see te email now? Apologies for the trouble Rob. If you still don't see the email please let me know and I'll ensure we send this manually. 

If your interested you can take a look at our fancy new web site...

https://plato.instantasp.co.uk/

Plato 1.1.1 due tomorrow adds new file sharing capabilities to Plato and now allows you to also attach files to any entities (topics, articles, docs, issues etc). You can also search within specific file types. These are new modules which as always you can choose to enable or disable. 1.1.1 also introduces some major performance improvements greatly reducing the number of datebase queries required to render each page and introduced a new extensibility model we are calling tag adapters - these allow modules to modify virtually any UI element within Plato. I will of course be sharing much more news tomrorow once I've compiled all the release notes. 

Best wishes for now Rob and thanks again for the feedback and trying Plato :)
