### ISSUE TITLE
Details on the License change

### ISSUE THREAD

**Issue by alweish** [InstantASP/Plato#34]
Hi!

Wasn't this an open-source project under the GNU General Public License 3.0!?

Can you share explanations about this change, Is that only for Plato 2.0? What about previous versions?

**Comment by RyanAtTouchBase** [comment]
Hi @alweish,

Thank you so much for your question. Apologies for not responding sooner. 

Plato did indeed start life as an open source project. Unfortunitly I could not make this work financially and so Plato went commercial after 6 months of being open source. 

I would love to keep Plato open source but also need to cover on going development & hosting costs. Similar to how GitHub support there free versions through enterprise customers once Plato is sustainable through paying customers I do intend to offer an open source or free version once again. 

I hope this offers some explanation. Please be assured I was sad to make Plato commercial  and hope again in the near future we can offer a completely free version. 

If I can assist further or provide any further information of course please don't hesitate to respond. 

Kindest Regards,

Ryan

**Comment by alweish** [comment]
Hi Rayn,

Thanks for the explanation, Hope to see this project growing and opened up for commercial use again.

Bests!
Alaa

**Comment by InstantASP** [comment]
Thanks @alweish. I appreicate your response and understanding. Please be assured my goal is to make Plato free & open source once things are sustainable. I'll be sharing some news on this very soon - just waiting for a few things to finalize. I sincerely appreicate your interest in Plato Alaa.
