### ISSUE TITLE
Thank you so much for the stars and support

### ISSUE THREAD

**Issue by InstantASP** [InstantASP/Plato#9]
Thank you so much to everyone who has recently stared Plato here on GitHub. I'm sincerely grateful for all your support and very happy to see what I've been working on the last 2 years has been so well received. Super special thank you to Dmitry Pavlov for helping me spread the word. 

Here are just a few of the kind comments received so far from a few lovely folks...

> **Naushad Sheikh** Congrats to team, Looking good.

> **Vedran Mandić** Gave the src a look... and that is one beautiful source, congratulations! And thank you for sharing it, one can learn a lot from peeking inside. Love that you have accepted totally the .NET Core ideas and API and went fully with it. Cool stuff you went with ADO.NET and sp/commands. Respect.

> **Đinh Đức Hải** Wow....... Plato is great.

> **Thabo Johannes Mosia** Looks great man, well done. We'll be checking it out

> **Ravi Kumar** - Awesome work

> **cybervivek** - congratulations for building such a beautiful product!

> **Vishwas Trivedi** Looks cool. I would love to be a contributor.

> **Ghosts** Absolutely love the look and features of Plato and excited to delve into it a bit deeper.

We also got a mention on the ASP.NET Community Stand Up...

https://youtu.be/6qAKwsbXCRE?t=715 - Thank you John 👯‍♂ 

Thank you to everyone above. Hopefully we'll have many more to share soon.

**Comment by bayesrule** [comment]
Expecting some work like this for a long while! Plato will definitely contribute to .Net Core's popularity!
